// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zariya.Data;

#nullable disable

namespace Zariya.Migrations
{
    [DbContext(typeof(ZariyaDbContext))]
    [Migration("20260617095143_SyncModelChanges")]
    partial class SyncModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zariya.Models.AdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("TargetRecordId")
                        .HasColumnType("int")
                        .HasColumnName("target_record_id");

                    b.Property<string>("TargetTable")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target_table");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int")
                        .HasColumnName("target_user_id");

                    b.HasKey("LogId")
                        .HasName("PK__Admin_Lo__9E2397E0E711467E");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Admin_Logs", (string)null);
                });

            modelBuilder.Entity("Zariya.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("province");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__031491A88C4C33C5");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Zariya.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complaint_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("reason");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int")
                        .HasColumnName("reported_user_id");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.HasKey("ComplaintId")
                        .HasName("PK__Complain__A771F61C227D8028");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("Zariya.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<int>("DonationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("donation_type_id");

                    b.Property<int>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<string>("HospitalName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("hospital_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("DonationId")
                        .HasName("PK__Donation__296B91DCC32BB79C");

                    b.HasIndex("CityId");

                    b.HasIndex("DonationTypeId");

                    b.HasIndex("DonorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequestId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Zariya.Models.DonationType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId")
                        .HasName("PK__Donation__2C000598D47A9E30");

                    b.HasIndex(new[] { "TypeName" }, "UQ__Donation__543C4FD9819D66E6")
                        .IsUnique();

                    b.ToTable("Donation_Types", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standard whole blood donation",
                            IsActive = true,
                            TypeName = "Whole Blood"
                        },
                        new
                        {
                            TypeId = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Platelet donation",
                            IsActive = true,
                            TypeName = "Platelets"
                        },
                        new
                        {
                            TypeId = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Plasma donation",
                            IsActive = true,
                            TypeName = "Plasma"
                        });
                });

            modelBuilder.Entity("Zariya.Models.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<string>("Availability")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("availability");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("cnic");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int?>("DonationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("donation_type_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAdminVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin_verified");

                    b.Property<DateOnly?>("LastDonated")
                        .HasColumnType("date")
                        .HasColumnName("last_donated");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_photo");

                    b.Property<short>("TotalDonations")
                        .HasColumnType("smallint")
                        .HasColumnName("total_donations");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("DonorId")
                        .HasName("PK__Donors__8B5B10F932A3880A");

                    b.HasIndex("CityId");

                    b.HasIndex(new[] { "Cnic" }, "UQ__Donors__35BD76A449E15B70")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__Donors__B9BE370E7689B7EA")
                        .IsUnique();

                    b.ToTable("Donors", t =>
                        {
                            t.HasTrigger("trg_Donors_Availability_Log");

                            t.HasTrigger("trg_Donors_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Zariya.Models.DonorAvailabilityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.HasKey("LogId")
                        .HasName("PK__Donor_Av__9E2397E08E9DCA58");

                    b.HasIndex("DonorId");

                    b.ToTable("Donor_Availability_Logs", (string)null);
                });

            modelBuilder.Entity("Zariya.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__7A6B2B8C18412D54");

                    b.HasIndex(new[] { "RequestId" }, "UQ__Feedback__18D3B90E2B1133A2")
                        .IsUnique();

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Zariya.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("cnic");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("MedicalCondition")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("medical_condition");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_photo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("normal")
                        .HasColumnName("urgency_level");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__4D5CE476407BE3D9");

                    b.HasIndex("CityId");

                    b.HasIndex(new[] { "Cnic" }, "UQ__Patients__35BD76A4F4665A44")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__Patients__B9BE370EC53E044E")
                        .IsUnique();

                    b.ToTable("Patients", t =>
                        {
                            t.HasTrigger("trg_Patients_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Zariya.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("BloodGroupNeeded")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group_needed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<string>("DonorResponse")
                        .HasColumnType("text")
                        .HasColumnName("donor_response");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit")
                        .HasColumnName("is_fulfilled");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("normal")
                        .HasColumnName("urgency");

                    b.HasKey("RequestId")
                        .HasName("PK__Requests__18D3B90F99CE93C1");

                    b.HasIndex("DonorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Requests", t =>
                        {
                            t.HasTrigger("trg_Requests_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Zariya.Models.SearchLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("AvailabilityFilter")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("availability_filter");

                    b.Property<string>("BloodGroupFilter")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group_filter");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<short>("ResultsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("results_count");

                    b.Property<int?>("SearchCityId")
                        .HasColumnType("int")
                        .HasColumnName("search_city_id");

                    b.Property<int?>("TypeFilter")
                        .HasColumnType("int")
                        .HasColumnName("type_filter");

                    b.HasKey("LogId")
                        .HasName("PK__Search_L__9E2397E0F319E3C3");

                    b.HasIndex("PatientId");

                    b.HasIndex("SearchCityId");

                    b.HasIndex("TypeFilter");

                    b.ToTable("Search_Logs", (string)null);
                });

            modelBuilder.Entity("Zariya.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerifyToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_verify_token");

                    b.Property<byte>("FailedAttempts")
                        .HasColumnType("tinyint")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_token_expires");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__tmp_ms_x__B9BE370FFC9EE8A4");

                    b.HasIndex(new[] { "Email" }, "UQ__tmp_ms_x__AB6E616489B3D586")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_Users_AfterInsert_CreateProfile");

                            t.HasTrigger("trg_Users_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Zariya.Models.AdminLog", b =>
                {
                    b.HasOne("Zariya.Models.User", "AdminUser")
                        .WithMany("AdminLogAdminUsers")
                        .HasForeignKey("AdminUserId")
                        .IsRequired()
                        .HasConstraintName("FK_AdminLogs_AdminUser");

                    b.HasOne("Zariya.Models.User", "TargetUser")
                        .WithMany("AdminLogTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK_AdminLogs_TargetUser");

                    b.Navigation("AdminUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Zariya.Models.Complaint", b =>
                {
                    b.HasOne("Zariya.Models.User", "ReportedUser")
                        .WithMany("ComplaintReportedUsers")
                        .HasForeignKey("ReportedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaints_ReportedUser");

                    b.HasOne("Zariya.Models.User", "Reporter")
                        .WithMany("ComplaintReporters")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaints_Reporter");

                    b.HasOne("Zariya.Models.User", "ResolvedByNavigation")
                        .WithMany("ComplaintResolvedByNavigations")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("FK_Complaints_ResolvedBy");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedByNavigation");
                });

            modelBuilder.Entity("Zariya.Models.Donation", b =>
                {
                    b.HasOne("Zariya.Models.City", "City")
                        .WithMany("Donations")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Donations_Cities");

                    b.HasOne("Zariya.Models.DonationType", "DonationType")
                        .WithMany("Donations")
                        .HasForeignKey("DonationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Donations_DonationTypes");

                    b.HasOne("Zariya.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .IsRequired()
                        .HasConstraintName("FK_Donations_Donors");

                    b.HasOne("Zariya.Models.Patient", "Patient")
                        .WithMany("Donations")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_Donations_Patients");

                    b.HasOne("Zariya.Models.Request", "Request")
                        .WithMany("Donations")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_Donations_Requests");

                    b.Navigation("City");

                    b.Navigation("DonationType");

                    b.Navigation("Donor");

                    b.Navigation("Patient");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Zariya.Models.Donor", b =>
                {
                    b.HasOne("Zariya.Models.City", "City")
                        .WithMany("Donors")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Donors_Cities");

                    b.HasOne("Zariya.Models.User", "User")
                        .WithOne("Donor")
                        .HasForeignKey("Zariya.Models.Donor", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Donors_Users");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zariya.Models.DonorAvailabilityLog", b =>
                {
                    b.HasOne("Zariya.Models.Donor", "Donor")
                        .WithMany("DonorAvailabilityLogs")
                        .HasForeignKey("DonorId")
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityLogs_Donors");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Zariya.Models.Feedback", b =>
                {
                    b.HasOne("Zariya.Models.Request", "Request")
                        .WithOne("Feedback")
                        .HasForeignKey("Zariya.Models.Feedback", "RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Requests");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Zariya.Models.Patient", b =>
                {
                    b.HasOne("Zariya.Models.City", "City")
                        .WithMany("Patients")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Patients_Cities");

                    b.HasOne("Zariya.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Zariya.Models.Patient", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patients_Users");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zariya.Models.Request", b =>
                {
                    b.HasOne("Zariya.Models.Donor", "Donor")
                        .WithMany("Requests")
                        .HasForeignKey("DonorId")
                        .HasConstraintName("FK_Requests_Donors");

                    b.HasOne("Zariya.Models.Patient", "Patient")
                        .WithMany("Requests")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_Patients");

                    b.Navigation("Donor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Zariya.Models.SearchLog", b =>
                {
                    b.HasOne("Zariya.Models.Patient", "Patient")
                        .WithMany("SearchLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SearchLogs_Patients");

                    b.HasOne("Zariya.Models.City", "SearchCity")
                        .WithMany("SearchLogs")
                        .HasForeignKey("SearchCityId")
                        .HasConstraintName("FK_SearchLogs_Cities");

                    b.HasOne("Zariya.Models.DonationType", "TypeFilterNavigation")
                        .WithMany("SearchLogs")
                        .HasForeignKey("TypeFilter")
                        .HasConstraintName("FK_SearchLogs_DonationTypes");

                    b.Navigation("Patient");

                    b.Navigation("SearchCity");

                    b.Navigation("TypeFilterNavigation");
                });

            modelBuilder.Entity("Zariya.Models.City", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Donors");

                    b.Navigation("Patients");

                    b.Navigation("SearchLogs");
                });

            modelBuilder.Entity("Zariya.Models.DonationType", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("SearchLogs");
                });

            modelBuilder.Entity("Zariya.Models.Donor", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("DonorAvailabilityLogs");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Zariya.Models.Patient", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Requests");

                    b.Navigation("SearchLogs");
                });

            modelBuilder.Entity("Zariya.Models.Request", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Zariya.Models.User", b =>
                {
                    b.Navigation("AdminLogAdminUsers");

                    b.Navigation("AdminLogTargetUsers");

                    b.Navigation("ComplaintReportedUsers");

                    b.Navigation("ComplaintReporters");

                    b.Navigation("ComplaintResolvedByNavigations");

                    b.Navigation("Donor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
